### PR TITLE
Length function

### PR DESCRIPTION
**Pull request by ntachukwu**
Fixes: #60

### CODE REVIEW

**Comment by Th3nn3ss** [comment]
`make test` returns this error
`cd wdl2cwl/tests && cwltest --tool cwltool --test cwl_tests.yaml
/bin/sh: 1: cwltest: not found
make: *** [Makefile:142: cwltest] Error 127
`

**Comment by mr-c** [comment]
@Th3nn3ss If you edit the [top comment](https://github.com/common-workflow-lab/wdl-cwl-translator/pull/92#issue-1027647594) to include the phrase "Fixes: #60 " then that issue will automatically be closed when the PR gets merged

**Comment by mr-c** [comment]
> Should I add all the other task workflows even though they are not explicitly handled by the code I just added? I believe there are two more tasks in the bcftools.wdl I left out.

Only if they contain `length()` WDL calls

**Comment by Th3nn3ss** [comment]
It's my pleasure. 

Should I always delete a branch after is't been merged?

**Comment by mr-c** [comment]
> Should I always delete a branch after it's been merged?

I would, but it is your fork, so that is up to you.

Now that you've made two contribution to this repository I'm going to give you permission to make branches directly here (and therefore you won't need your fork). We've set branches in this repository to automatically be deleted after merging.

**Pull request merged**
