### PR TITLE
Handle expression placeholder option 'sep'

### LINKED ISSUE #26: Expression Placeholder Option 'sep' is not handled
eg: ~{sep=", " array_value}
https://github.com/openwdl/wdl/blob/main/versions/1.1/SPEC.md#-expression-placeholder-options mentions that expression placeholder options are deprecated and will be removed in WDL 2.0.

https://github.com/biowdl/tasks/blob/develop/seqtk.wdl#L40 uses the mentioned expression placeholder option.

### PR DESCRIPTION
**Pull request by dinithiW**
Fixes #26

### CODE REVIEW

**Review by mr-c — CHANGES_REQUESTED** [review]
Looks good! Please run with sample data and leave a note where you got the sample data.

Looks like `vt.{cwl,wdl}` isn't applicable for this PR; can you remove those?

**Comment by mr-c** [comment]
Also, please add back in the `sep=`s that got removed from the existing tests; thanks!

**Comment by dinithiW** [comment]
> Looks good! Please run with sample data and leave a note where you got the sample data.

```output path not found in container (error unless declared type is optional) :: output: "sdf", path: "seq_data.sdf"```
```wdl.t:Format task Format (rtg.wdl Ln 25 Col 1) failed :: dir: "rtg/20210817_190323_Format", error: "OutputError", message: "File/Directory path not found in task output sdf", node: "decl-sdf"```
```miniwdl-run File/Directory path not found in task output sdf :: error: "OutputError", node: "decl-sdf", dir: "rtg/20210817_190323_Format"```

I get this error when I run the WDL document. Any idea what could be causing it?

**Comment by mr-c** [comment]
> I get this error when I run the WDL document. Any idea what could be causing it?

Which WDL document? Did you edit it, at all?

**Comment by dinithiW** [comment]
> > I get this error when I run the WDL document. Any idea what could be causing it?
> 
> Which WDL document? Did you edit it, at all?

rtg.wdl. This is the original WDL document. Only commented time_minutes in the input section. The original document had two documents out of which I chose only one

**Comment by mr-c** [comment]
Can you share how you ran `rtd.wdl`?

**Comment by dinithiW** [comment]
> Can you share how you ran `rtd.wdl`?

```miniwdl run rtg.wdl inputFiles=reference.fasta --verbose  ```
reference.fasta used was https://github.com/biowdl/clinical-validation/blob/6d1d9104df02ef5d9e6742bd98683bbfa7a88459/tests/data/reference.fasta

**Comment by mr-c** [comment]
> > Can you share how you ran `rtd.wdl`?
> 
> `miniwdl run rtg.wdl inputFiles=reference.fasta --verbose `
> reference.fasta used was https://github.com/biowdl/clinical-validation/blob/6d1d9104df02ef5d9e6742bd98683bbfa7a88459/tests/data/reference.fasta

The resulting output is a Directory, not a FIle; the original WDL is wrong, SDF format is a directory as documented in https://www.animalgenome.org/bioinfo/resources/manuals/RTGOperationsManual.pdf#page=14

> The format command converts the contents of sequence data files (FASTA/FASTQ/SAM/BAM) into the RTG Sequence Data File (SDF) format. This step ensures efficient processing of very large data sets, by organizing the data into multiple binary files within a named directory. 

Can you fix the WDL file here to output a `Directory` and send a PR to https://github.com/biowdl/tasks/ with the same fix?

**Comment by dinithiW** [comment]
> The resulting output is a Directory, not a FIle; the original WDL is wrong, SDF format is a directory as documented in https://www.animalgenome.org/bioinfo/resources/manuals/RTGOperationsManual.pdf#page=14
> 
> > The format command converts the contents of sequence data files (FASTA/FASTQ/SAM/BAM) into the RTG Sequence Data File (SDF) format. This step ensures efficient processing of very large data sets, by organizing the data into multiple binary files within a named directory.
> 

I can't find a directory type in WDL

**Comment by mr-c** [comment]
> I can't find a directory type in WDL

Ah, I thought they had added it already, seems not yet: https://github.com/openwdl/wdl/blob/main/versions/Differences.md#11-to-development

Then you can use `Array[File]`, yes?

**Comment by dinithiW** [comment]
> Then you can use `Array[File]`, yes?

I'm not sure how to. I tried ```Array[File] sdf = [outputPath]``` which gives the same error as before. Then I tried  ```Array[File] sdf = glob("*.sdf")``` which doesn't give an error but there's no output.

**Comment by mr-c** [comment]
> > Then you can use `Array[File]`, yes?
> 
> I'm not sure how to. I tried `Array[File] sdf = [outputPath]` which gives the same error as before. Then I tried `Array[File] sdf = glob("*.sdf")` which doesn't give an error but there's no output.

How about `Array[File]+ sdf = glob("~{outputPath}/*")` ?

**Comment by dinithiW** [comment]
> How about `Array[File]+ sdf = glob("~{outputPath}/*")` ?

I get an output but I'm not sure whether that's what is expected. 11 folders having the following files were created.

```{
  "Format.sdf": [
    "/test_files/rtg/20210819_192659_Format/out/sdf/00/done",
    "/test_files/rtg/20210819_192659_Format/out/sdf/01/format.log",
    "/test_files/rtg/20210819_192659_Format/out/sdf/02/mainIndex",
    "/test_files/rtg/20210819_192659_Format/out/sdf/03/nameIndex0",
    "/test_files/rtg/20210819_192659_Format/out/sdf/04/namedata0",
    "/test_files/rtg/20210819_192659_Format/out/sdf/05/namepointer0",
    "/test_files/rtg/20210819_192659_Format/out/sdf/06/progress",
    "/test_files/rtg/20210819_192659_Format/out/sdf/07/seqdata0",
    "/test_files/rtg/20210819_192659_Format/out/sdf/08/seqpointer0",
    "/test_files/rtg/20210819_192659_Format/out/sdf/09/sequenceIndex0",
    "/test_files/rtg/20210819_192659_Format/out/sdf/10/summary.txt"
  ]
}```

**Comment by mr-c** [comment]
> > How about `Array[File]+ sdf = glob("~{outputPath}/*")` ?
> 
> I get an output but I'm not sure whether that's what is expected. 11 folders having the following files were created.
> 
> ```
>   "Format.sdf": [
>     "/test_files/rtg/20210819_192659_Format/out/sdf/00/done",
>     "/test_files/rtg/20210819_192659_Format/out/sdf/01/format.log",
>     "/test_files/rtg/20210819_192659_Format/out/sdf/02/mainIndex",
>     "/test_files/rtg/20210819_192659_Format/out/sdf/03/nameIndex0",
>     "/test_files/rtg/20210819_192659_Format/out/sdf/04/namedata0",
>     "/test_files/rtg/20210819_192659_Format/out/sdf/05/namepointer0",
>     "/test_files/rtg/20210819_192659_Format/out/sdf/06/progress",
>     "/test_files/rtg/20210819_192659_Format/out/sdf/07/seqdata0",
>     "/test_files/rtg/20210819_192659_Format/out/sdf/08/seqpointer0",
>     "/test_files/rtg/20210819_192659_Format/out/sdf/09/sequenceIndex0",
>     "/test_files/rtg/20210819_192659_Format/out/sdf/10/summary.txt"
>   ]
> ```

as long as that matches the output from running the CWL version, then that is good enough for us.

**Comment by dinithiW** [comment]
> as long as that matches the output from running the CWL version, then that is good enough for us.

How should the inputs be given in the .yml file? I tried ```inputFiles: [reference.fasta]``` which gives this error
  
```the `inputFiles` field is not valid because tried array of <File> but item is invalid because  is not a dict```

**Comment by mr-c** [comment]
> > as long as that matches the output from running the CWL version, then that is good enough for us.
> 
> How should the inputs be given in the .yml file? I tried `inputFiles: [reference.fasta]` which gives this error
> 
> `` the `inputFiles` field is not valid because tried array of <File> but item is invalid because is not a dict ``

See `example_file` in `inp-job.yml` in https://www.commonwl.org/user_guide/03-input/index.html ; but make it an array

``` cwl
inputFiles:
  - class: File
    path: reference.fasta
```

or on the command line `cwltool rtg.cwl --inputFiles reference.fasta` (add additional `--inputFiles` for more inputs)

**Comment by dinithiW** [comment]
> See `example_file` in `inp-job.yml` in https://www.commonwl.org/user_guide/03-input/index.html ; but make it an array
> 
> ```cwl
> inputFiles:
>   - class: File
>     path: reference.fasta
> ```
> 
> or on the command line `cwltool rtg.cwl --inputFiles reference.fasta` (add additional `--inputFiles` for more inputs)

Oh no :( 
```Error: File not found: "[object"
Error: File not found: "Object]"
Error: There were 2 invalid input file paths
WARNING [job Format] completed permanentFail
```

I changed the output in the cwl file to
```
outputs:
  - id: sdf
    type: 
      - items: File
        type: array
    outputBinding:
        glob: "$(inputs.outputPath)/*"
```
I hope that's correct

**Comment by mr-c** [comment]
> I changed the output in the cwl file to
> 
> ```
> outputs:
>   - id: sdf
>     type: 
>       - items: File
>         type: array
>     outputBinding:
>         glob: "$(inputs.outputPath)/*"
> ```
> 
> I hope that's correct

Can you push your code changes? The indentation doesn't seem correct.

**Comment by dinithiW** [comment]
Add updated rtg.cwl file

**Review by mr-c — CHANGES_REQUESTED** [review]
Can you fix this error? https://github.com/common-workflow-lab/wdl-cwl-translator/pull/51/checks?check_run_id=3379090600#step:7:208

**Comment by dinithiW** [comment]
> Can you fix this error? https://github.com/common-workflow-lab/wdl-cwl-translator/pull/51/checks?check_run_id=3379090600#step:7:208

I created a separate PR for this #69

**Review by mr-c — APPROVED** [review]

**Pull request merged**
