### PR TITLE
Error reports include line and column number, if available

### LINKED ISSUE #129: Make use of the "pos" attribute on MiniWDL objects for better error messages
The `pos` attribute is of type [`SourcePosition`](https://github.com/chanzuckerberg/miniwdl/blob/5b66f2f0b5101a70bae9df51bc7772a93189ba51/WDL/_error_util.py#L4).

Example:
> SourcePosition(uri='wdl_files/whatshap-Phase.wdl', abspath='/home/michael/wdl2cwl/wdl2cwl/tests/wdl_files/whatshap-Phase.wdl', line=54, column=54, end_line=54, end_column=57)

In schema-salad using CWL project we have a similar attribute via our use of `ruamel.yaml` that we using with our `SourceLine` objects to automatically wrap exceptions with details on the item and location in the original file: https://github.com/common-workflow-language/schema_salad/blob/661fb0fa8c745ed70253dda93bd12002007f6b33/schema_salad/sourceline.py#L232

For internal miniwdl use, they have something similar [`multi_context`](https://github.com/chanzuckerberg/miniwdl/blob/b0f67b15e99e9ed3454c0f44c1ce9d0ba2cff60d/WDL/Error.py#L281) between only trapping `WDL.Error.{ValidationError,MultipleValidationErrors}` and its usage model means that I don't feel it makes sense for our needs in `wdl2cwl`

### PR DESCRIPTION
**Pull request by mr-c**
Fixes #129

### CODE REVIEW

**Review by kinow — APPROVED** [review]
Looks good to me! And I never used that approach to wrap the errors. Will take a better look later to learn/remember it for a future project. Great idea :+1: 

Approving pending only CI to pass.

**Comment by kinow** [comment]
(disabled auto-merge because didn't know if you were going to merge this one first, or merge Dennis' PR first :+1:, now :sleeping_bed:  )

**Comment by Th3nn3ss** [comment]
This looks cool. So essentially anywhere I am raising an error, I should use this?

**Review by Th3nn3ss — APPROVED** [review]
Will love to make use of it.

**Comment by mr-c** [comment]
> This looks cool. So essentially anywhere I am raising an error, I should use this?

Yes, and also where some other code might generate an exception related to a specific miniWDL object:

https://github.com/common-workflow-lab/wdl-cwl-translator/pull/141/files#diff-b5a65c2befbbd0b6453805272729b622f41b2be683f8258432e08f4370332265R162

https://github.com/common-workflow-lab/wdl-cwl-translator/pull/141/files#diff-b5a65c2befbbd0b6453805272729b622f41b2be683f8258432e08f4370332265R175

https://github.com/common-workflow-lab/wdl-cwl-translator/pull/141/files#diff-b5a65c2befbbd0b6453805272729b622f41b2be683f8258432e08f4370332265R358

https://github.com/common-workflow-lab/wdl-cwl-translator/pull/141/files#diff-b5a65c2befbbd0b6453805272729b622f41b2be683f8258432e08f4370332265R392

**Comment by kinow** [comment]
Loved it! Tested the workflow from #77

**Pull request merged**
